# Generated by Django 5.0.1 on 2024-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='hr-1.jpg', upload_to='uploads/articles'),
        ),
    ]
