# Generated by Django 5.0.1 on 2024-01-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_article_options_alter_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
